### ISSUE TITLE
Behavior and EBNF mismatch regarding `Ignored`

### ISSUE THREAD

**Issue by KevinXuxuxu** [karminski/pineapple#1]
e.g. The following pineapple source code should raise lexer error (notice the whitespace between `$` and `a`), but still passed:
```
$ a = "pen pineapple apple pen."
print($a)
```
More generally speaking, `Ignored` in EBNF does not appear between _every_ pair of other tokens, so should not be skipped in lexer whenever seen. Instead, it's better to treat `Ignored` as an individual token so that it can be correctly parsed.

**Comment by karminski** [comment]
Thanks, I will fix it later.

**Comment by karminski** [comment]
FIXED, see [https://github.com/karminski/pineapple/commit/23cee0a65a2df89e28906787ea2b58c1f3916626](https://github.com/karminski/pineapple/commit/23cee0a65a2df89e28906787ea2b58c1f3916626).

Added the LookAheadAndSkip() function for check and skip Ignored token.
