### ISSUE TITLE
你好，请问parseStatement是否少了对TOKEN_IGNORED的处理

### ISSUE THREAD

**Issue by yiippee** [karminski/pineapple#2]
感谢你的教程，请教一个问题，parseStatement是否少了对TOKEN_IGNORED的处理，源码文本一开始就有一些可忽略的字符串的话，可能就需要处理一下？
谢谢，还是我哪里理解错了？
```
func parseStatement(lexer *Lexer) (Statement, error) {
	// LookAhead() 没有参数, 但执行它的时候, 他会 LookAhead (向前看) 一个 Token, 告诉我们下一个 Token 是什么.
	switch lexer.LookAhead() {
	case TOKEN_PRINT:
		return parsePrint(lexer) // 如果是 TOKEN_PRINT ("print"), 那么肯定就是 Print 语句了! 我们就调用 parsePrint().
	case TOKEN_VAR_PREFIX:
		return parseAssignment(lexer)
	//case TOKEN_IGNORED:  // 这里好像需要处理 TOKEN_IGNORED
	//    lexer.nextTokenLineNum = 0   nextTokenLineNum  具体代表什么含义呢？
	//	return nil, nil 
	default:
		return nil, errors.New("parseStatement(): unknown Statement.")
	}
}
```

**Comment by karminski** [comment]
Thanks, fixed https://github.com/karminski/pineapple/commit/58379018fdf0a021adfdb1f352ad17c0c804f4cf

感谢提交 issue, 针对源码以 ```IGNORED_TOKEN``` 开头的情况, 在 parseStatement() 中增加了 ```lexer.LookAheadAndSkip(TOKEN_IGNORED)``` 以解决该问题. 

另, ```nextTokenLineNum``` 主要用于缓存已经解析的 next token. 详见: https://zhuanlan.zhihu.com/p/342036670 描述了 ```nextTokenLineNum``` 的用途.
