### ISSUE TITLE
Could you provide a cpp implementation?

### ISSUE THREAD

**Issue by uran0sH** [karminski/pineapple#5]
C/C++ is used by a lot of people. So I thought that cpp implementation is convenient for more people to learn. Now I am trying to implement it, but I meet some trouble. So u or someone else could provide a cpp implementation?

**Comment by karminski** [comment]
This repo is just a demo for the “write-a-programming-language-in-450-lines” repo, and I have no plan for C/C++ implementation. Sorry for that.

**Comment by YianAndCode** [comment]
I have worked for the implementation of C for a while, but I found it a little difficult for me, so I paused it, maybe I will restart it soon, if you are interested in it, please visit https:/ /github .com/YianAndCode/pineapple-c

**Comment by YianAndCode** [comment]
Hi, I finished the implementation of C, please visit [https://github.com/YianAndCode/pineapple-c](https://github.com/YianAndCode/pineapple-c)

**Comment by uran0sH** [comment]
> Hi, I finished the implementation of C, please visit https://github.com/YianAndCode/pineapple-c

Thank you very much.
